// Spiral vase-mode G-code generator.
// Produces: brim → solid bottom layers → one continuous spiralized
// outer wall (no seams, no retractions), using the exact same
// radiusAt() the 3D preview renders.

import { radiusAt, maxRadius } from './vase.js';
import { PRINTERS, MATERIALS, resolveTemps } from './printers.js';
import { TAU } from './state.js';

const FILAMENT_AREA = Math.PI * (1.75 / 2) ** 2; // mm^2
const DENSITY = { PLA: 1.24, PETG: 1.27 };       // g/cm^3
const MAX_FLOW = { PLA: 12, PETG: 9 };           // mm^3/s volumetric limit

function fmt(n, d = 2) {
  let s = n.toFixed(d);
  if (s.includes('.')) s = s.replace(/\.?0+$/, '');
  return s === '-0' ? '0' : s;
}

export function generateGcode(state) {
  const { shape, texture, printer } = state;
  const preset = PRINTERS[printer.model];
  const mat = MATERIALS[printer.material];
  const temps = resolveTemps(printer.model, printer.material);
  const lh = printer.layerHeight;
  const lw = printer.lineWidth;
  const ePerMm = (lh * lw) / FILAMENT_AREA;
  const [bedX, bedY, bedZ] = preset.volume;
  const cx = bedX / 2, cy = bedY / 2;

  // Speeds (mm/s), respecting the material volumetric flow limit.
  const flowCap = MAX_FLOW[printer.material] / (lh * lw);
  const wallSpeed = Math.min(mat.maxSpeed, flowCap, 45);
  const firstSpeed = Math.min(20, wallSpeed);
  const solidSpeed = Math.min(mat.maxSpeed, flowCap, 50);
  const travelSpeed = 150;

  const warnings = [];
  const rMax = maxRadius(shape, texture);
  const footprint = (rMax + printer.brimLoops * lw) * 2;
  if (footprint > Math.min(bedX, bedY) - 10) {
    warnings.push(`Model + brim (Ø${fmt(footprint, 0)} mm) exceeds the ${preset.label} bed.`);
  }
  if (shape.height > bedZ) {
    warnings.push(`Height ${fmt(shape.height, 0)} mm exceeds the ${bedZ} mm build volume.`);
  }

  const lines = [];
  const toolpath = []; // [{ type, points: [x,y,z,...] }] for the 3D preview
  let E = 0, timeS = 0;
  let lastX = cx, lastY = cy, lastZ = 0;

  const push = s => lines.push(s);

  function travel(x, y, z, speed = travelSpeed) {
    push(`G0 X${fmt(x)} Y${fmt(y)} Z${fmt(z, 3)} F${Math.round(speed * 60)}`);
    timeS += Math.hypot(x - lastX, y - lastY, z - lastZ) / speed;
    lastX = x; lastY = y; lastZ = z;
  }

  function extrude(x, y, z, speed) {
    const d = Math.hypot(x - lastX, y - lastY, z - lastZ);
    E += d * ePerMm;
    push(`G1 X${fmt(x)} Y${fmt(y)} Z${fmt(z, 3)} E${E.toFixed(5)} F${Math.round(speed * 60)}`);
    timeS += d / speed;
    lastX = x; lastY = y; lastZ = z;
  }

  // Sample a closed loop of the vase contour at height zSample (mm),
  // radially offset by `off` mm, printed at nozzle height zPrint.
  function loopPoints(zSample, off, segs) {
    const pts = [];
    for (let i = 0; i <= segs; i++) {
      const th = (i / segs) * TAU;
      const r = Math.max(0.2, radiusAt(shape, texture, th, zSample) + off);
      pts.push([cx + Math.cos(th) * r, cy + Math.sin(th) * r]);
    }
    return pts;
  }

  function segsFor(radius) {
    let s = Math.ceil((TAU * Math.max(radius, 5)) / 0.8);
    if (texture.pattern !== 'smooth') s = Math.max(s, texture.frequency * 10);
    return Math.min(800, Math.max(96, s));
  }

  function printLoop(zSample, off, zPrint, speed, type) {
    const segs = segsFor(radiusAt(shape, texture, 0, zSample) + off);
    const pts = loopPoints(zSample, off, segs);
    travel(pts[0][0], pts[0][1], zPrint);
    const tp = [];
    for (let i = 1; i < pts.length; i++) {
      extrude(pts[i][0], pts[i][1], zPrint, speed);
      tp.push(pts[i][0] - cx, zPrint, pts[i][1] - cy);
    }
    toolpath.push({ type, points: tp });
  }

  // ---------- header ----------
  push(`; generated by KJD GCODE vase designer`);
  push(`; printer: ${preset.label}  material: ${printer.material}  nozzle: ${printer.nozzle} mm`);
  push(`; layer height: ${lh} mm  line width: ${lw} mm  vase mode: spiral`);
  push(`; height: ${fmt(shape.height, 1)} mm  max radius: ${fmt(rMax, 1)} mm`);
  push(`;TYPE:Custom`);

  const startCode = (printer.model === 'custom' && printer.customStart.trim())
    ? printer.customStart : preset.start;
  push(startCode
    .replaceAll('{nozzle_temp}', temps.nozzleTemp)
    .replaceAll('{bed_temp}', temps.bedTemp)
    .replaceAll('{fan}', temps.fanPWM));
  push('M82 ; absolute extrusion');
  push('G92 E0');
  push('M106 S0 ; fan off for first layer');
  timeS += 150; // homing + heating estimate

  // ---------- brim ----------
  const z0 = lh;
  if (printer.brimLoops > 0) {
    push(`;LAYER:0`);
    push(`;TYPE:Brim`);
    for (let b = printer.brimLoops; b >= 1; b--) {
      printLoop(0, b * lw * 0.98, z0, firstSpeed, 'brim');
    }
  }

  // ---------- solid bottom ----------
  for (let j = 1; j <= printer.bottomLayers; j++) {
    const zPrint = j * lh;
    if (j > 1 || printer.brimLoops === 0) push(`;LAYER:${j - 1}`);
    push(`;TYPE:Bottom`);
    if (j === 2) push(`M106 S${temps.fanPWM}`);
    const speed = j === 1 ? firstSpeed : solidSpeed;
    // concentric fill: perimeter inwards to the centre
    const rc = radiusAt(shape, texture, 0, zPrint);
    const nLoops = Math.max(1, Math.floor(rc / (lw * 0.95)));
    for (let i = 0; i < nLoops; i++) {
      printLoop(zPrint, -i * lw * 0.95, zPrint, speed, 'bottom');
    }
  }

  // ---------- spiral wall ----------
  if (printer.bottomLayers < 2) push(`M106 S${temps.fanPWM}`);
  push(`;TYPE:Wall-spiral`);
  let layer = printer.bottomLayers;
  const zStart = printer.bottomLayers * lh;
  const spiralHeight = shape.height - zStart;
  if (spiralHeight > 0) {
    const revs = spiralHeight / lh;
    const segs = segsFor(rMax);
    const totalSteps = Math.ceil(revs * segs);
    const tp = [];
    // move to spiral start
    {
      const r = radiusAt(shape, texture, 0, zStart);
      travel(cx + r, cy, zStart);
    }
    let lastLayerMark = -1;
    for (let s = 1; s <= totalSteps; s++) {
      const th = (s / segs) * TAU;
      const z = zStart + (s / totalSteps) * spiralHeight;
      const zSample = Math.min(z, shape.height);
      const r = radiusAt(shape, texture, th, zSample);
      const lm = Math.floor((z - zStart) / lh);
      if (lm !== lastLayerMark) {
        push(`;LAYER:${layer + lm}`);
        lastLayerMark = lm;
      }
      extrude(cx + Math.cos(th) * r, cy + Math.sin(th) * r, z, wallSpeed);
      tp.push(lastX - cx, z, lastY - cy);
    }
    toolpath.push({ type: 'wall', points: tp });
    layer += Math.ceil(revs);
  }

  // ---------- end ----------
  const endCode = (printer.model === 'custom' && printer.customEnd.trim())
    ? printer.customEnd : preset.end;
  push(endCode);
  push('; end of print');

  const gcode = lines.join('\n') + '\n';
  const filamentMm = E;
  const filamentG = (filamentMm * FILAMENT_AREA / 1000) * (DENSITY[printer.material] ?? 1.24);

  return {
    gcode,
    toolpath,
    stats: {
      layers: layer,
      filamentMm,
      filamentG,
      timeS,
      bytes: gcode.length,
      warnings,
    },
  };
}

export function formatTime(s) {
  const h = Math.floor(s / 3600);
  const m = Math.round((s % 3600) / 60);
  return h > 0 ? `${h}h ${m}m` : `${m}m`;
}
